### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by Rizora** [nicolas98320/Podcast-swift#26]
Podcast-swift-master/Pods/Target Support Files/Pods-Podcast/Pods-Podcast.release.xcconfig: unable to open file (in target "Podcast" in project "Podcast") (in target 'Podcast')

I'm unable to locate this file...

**Comment by Rizora** [comment]
is a resource missing or is the podfile not working?

**Comment by nicolas98320** [comment]
It's working fine for me, did you run the command `pod install` ?

**Comment by Rizora** [comment]
yes.

**Comment by Rizora** [comment]
correction I cleaned the build folder and the errors disappeared... lesson run pod install before opening. a great way to help others avoid this would be to put download Pods and run pod install before opening the project.
